/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MyApps;

import java.sql.Date;
import java.sql.SQLException;

import javax.swing.JOptionPane;

/**
 *
 * @author allen
 */
import MyLibs.*;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

public class StudentDashboard extends javax.swing.JFrame {

    private User originalUser;

    /**
     * Creates new form TeacherDashboard
     */
    public StudentDashboard() {
        initComponents();
        Manager manager = Manager.getInstance();
        originalUser = manager.getCurrentUser();
        populateFields();
        populateTables();
    }

    public StudentDashboard(User user) {
        initComponents();
        Manager manager = Manager.getInstance();
        manager.setCurrentUser(user);
        originalUser = user; // Use the provided User object
        populateFields();
        populateTables();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        CampusMateLogo = new javax.swing.JLabel();
        coursesPanel = new javax.swing.JPanel();
        coursesText = new javax.swing.JLabel();
        coursesIcon = new javax.swing.JLabel();
        tasksPanel = new javax.swing.JPanel();
        tasksText = new javax.swing.JLabel();
        tasksIcon = new javax.swing.JLabel();
        editMyProfilePanel = new javax.swing.JPanel();
        editMyProfileText = new javax.swing.JLabel();
        editMyProfileIcon = new javax.swing.JLabel();
        signOutPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        headerPanel1 = new javax.swing.JPanel();
        headerText = new javax.swing.JLabel();
        fullnameText = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        headerDivider = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        coursesTab = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        coursesTable = new javax.swing.JTable();
        tasksTab = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tasksTable = new javax.swing.JTable();
        createViewSubmission = new javax.swing.JPanel();
        headerText1 = new javax.swing.JLabel();
        editMyProfileTab = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        birthdateField = new javax.swing.JTextField();
        genderField = new javax.swing.JTextField();
        changePasswordLink = new javax.swing.JLabel();
        saveChangesButton = new javax.swing.JPanel();
        saveChangesText = new javax.swing.JLabel();
        resetChangesButton = new javax.swing.JPanel();
        resetChangesText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 800));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1200, 800));
        jPanel1.setMinimumSize(new java.awt.Dimension(1200, 800));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(35, 35, 35));
        jPanel2.setMaximumSize(new java.awt.Dimension(230, 800));
        jPanel2.setMinimumSize(new java.awt.Dimension(230, 800));
        jPanel2.setPreferredSize(new java.awt.Dimension(230, 800));

        CampusMateLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/img02_dashboard_logo.png"))); // NOI18N

        coursesPanel.setBackground(new java.awt.Color(67, 67, 67));
        coursesPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        coursesPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                coursesPanelMouseReleased(evt);
            }
        });

        coursesText.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        coursesText.setForeground(new java.awt.Color(219, 219, 219));
        coursesText.setText("Courses");

        coursesIcon.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        coursesIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/img30_courses_selected.png"))); // NOI18N

        javax.swing.GroupLayout coursesPanelLayout = new javax.swing.GroupLayout(coursesPanel);
        coursesPanel.setLayout(coursesPanelLayout);
        coursesPanelLayout.setHorizontalGroup(
            coursesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, coursesPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(coursesIcon)
                .addGap(18, 18, 18)
                .addComponent(coursesText)
                .addGap(100, 100, 100))
        );
        coursesPanelLayout.setVerticalGroup(
            coursesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coursesPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(coursesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(coursesIcon)
                    .addComponent(coursesText))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        tasksPanel.setBackground(new java.awt.Color(35, 35, 35));
        tasksPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tasksPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tasksPanelMouseReleased(evt);
            }
        });
        tasksPanel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tasksPanelKeyReleased(evt);
            }
        });

        tasksText.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        tasksText.setForeground(new java.awt.Color(112, 110, 110));
        tasksText.setText("Tasks");

        tasksIcon.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        tasksIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/img33_tasks_unselected.png"))); // NOI18N

        javax.swing.GroupLayout tasksPanelLayout = new javax.swing.GroupLayout(tasksPanel);
        tasksPanel.setLayout(tasksPanelLayout);
        tasksPanelLayout.setHorizontalGroup(
            tasksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tasksPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tasksIcon)
                .addGap(18, 18, 18)
                .addComponent(tasksText)
                .addGap(118, 118, 118))
        );
        tasksPanelLayout.setVerticalGroup(
            tasksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tasksPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(tasksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tasksIcon)
                    .addComponent(tasksText))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        editMyProfilePanel.setBackground(new java.awt.Color(35, 35, 35));
        editMyProfilePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editMyProfilePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                editMyProfilePanelMouseReleased(evt);
            }
        });

        editMyProfileText.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        editMyProfileText.setForeground(new java.awt.Color(112, 110, 110));
        editMyProfileText.setText("Edit my Profile");

        editMyProfileIcon.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        editMyProfileIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/img35_editMyProfile_unselected.png"))); // NOI18N

        javax.swing.GroupLayout editMyProfilePanelLayout = new javax.swing.GroupLayout(editMyProfilePanel);
        editMyProfilePanel.setLayout(editMyProfilePanelLayout);
        editMyProfilePanelLayout.setHorizontalGroup(
            editMyProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editMyProfilePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(editMyProfileIcon)
                .addGap(18, 18, 18)
                .addComponent(editMyProfileText)
                .addGap(49, 49, 49))
        );
        editMyProfilePanelLayout.setVerticalGroup(
            editMyProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editMyProfilePanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(editMyProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editMyProfileText)
                    .addComponent(editMyProfileIcon))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        signOutPanel.setBackground(new java.awt.Color(49, 49, 49));
        signOutPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signOutPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                signOutPanelMouseReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(219, 219, 219));
        jLabel9.setText("Sign Out");

        javax.swing.GroupLayout signOutPanelLayout = new javax.swing.GroupLayout(signOutPanel);
        signOutPanel.setLayout(signOutPanelLayout);
        signOutPanelLayout.setHorizontalGroup(
            signOutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signOutPanelLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        signOutPanelLayout.setVerticalGroup(
            signOutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(CampusMateLogo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(coursesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tasksPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(editMyProfilePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(signOutPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(CampusMateLogo)
                .addGap(67, 67, 67)
                .addComponent(coursesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tasksPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editMyProfilePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 414, Short.MAX_VALUE)
                .addComponent(signOutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 765));

        headerPanel1.setBackground(new java.awt.Color(255, 255, 255));

        headerText.setBackground(new java.awt.Color(67, 67, 67));
        headerText.setFont(new java.awt.Font("Helvetica", 1, 36)); // NOI18N
        headerText.setForeground(new java.awt.Color(67, 67, 67));
        headerText.setText("Dashboard");

        fullnameText.setBackground(new java.awt.Color(67, 67, 67));
        fullnameText.setFont(new java.awt.Font("Helvetica", 1, 24)); // NOI18N
        fullnameText.setForeground(new java.awt.Color(67, 67, 67));
        fullnameText.setText("Fullname");

        jLabel3.setBackground(new java.awt.Color(67, 67, 67));
        jLabel3.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(67, 67, 67));
        jLabel3.setText("Student");

        headerDivider.setBackground(new java.awt.Color(112, 110, 110));
        headerDivider.setPreferredSize(new java.awt.Dimension(0, 2));

        javax.swing.GroupLayout headerDividerLayout = new javax.swing.GroupLayout(headerDivider);
        headerDivider.setLayout(headerDividerLayout);
        headerDividerLayout.setHorizontalGroup(
            headerDividerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 933, Short.MAX_VALUE)
        );
        headerDividerLayout.setVerticalGroup(
            headerDividerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout headerPanel1Layout = new javax.swing.GroupLayout(headerPanel1);
        headerPanel1.setLayout(headerPanel1Layout);
        headerPanel1Layout.setHorizontalGroup(
            headerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(headerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(headerPanel1Layout.createSequentialGroup()
                        .addComponent(headerText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(headerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fullnameText, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(headerDivider, javax.swing.GroupLayout.PREFERRED_SIZE, 933, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        headerPanel1Layout.setVerticalGroup(
            headerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanel1Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(headerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerPanel1Layout.createSequentialGroup()
                        .addComponent(fullnameText)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel3))
                    .addComponent(headerText))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(headerDivider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jPanel1.add(headerPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 990, -1));

        coursesTab.setBackground(new java.awt.Color(255, 255, 255));

        coursesTable.setAutoCreateRowSorter(true);
        coursesTable.setBackground(new java.awt.Color(255, 255, 255));
        coursesTable.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        coursesTable.setForeground(new java.awt.Color(0, 0, 0));
        coursesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course Code", "Course Title", "Average Grade", "Attendance Rate"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        coursesTable.setRowHeight(40);
        jScrollPane1.setViewportView(coursesTable);

        javax.swing.GroupLayout coursesTabLayout = new javax.swing.GroupLayout(coursesTab);
        coursesTab.setLayout(coursesTabLayout);
        coursesTabLayout.setHorizontalGroup(
            coursesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coursesTabLayout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 935, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        coursesTabLayout.setVerticalGroup(
            coursesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coursesTabLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab1", coursesTab);

        tasksTab.setBackground(new java.awt.Color(255, 255, 255));

        tasksTable.setAutoCreateRowSorter(true);
        tasksTable.setBackground(new java.awt.Color(249, 249, 249));
        tasksTable.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        tasksTable.setForeground(new java.awt.Color(0, 0, 0));
        tasksTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Submission ID", "Course Code", "Course Title", "Task Title", "Status", "Grade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tasksTable.setRowHeight(40);
        tasksTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tasksTableMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tasksTable);

        createViewSubmission.setBackground(new java.awt.Color(30, 56, 115));
        createViewSubmission.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createViewSubmission.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                createViewSubmissionMouseReleased(evt);
            }
        });

        headerText1.setBackground(new java.awt.Color(67, 67, 67));
        headerText1.setFont(new java.awt.Font("Helvetica", 1, 24)); // NOI18N
        headerText1.setForeground(new java.awt.Color(255, 255, 255));
        headerText1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerText1.setText("Create Submission");

        javax.swing.GroupLayout createViewSubmissionLayout = new javax.swing.GroupLayout(createViewSubmission);
        createViewSubmission.setLayout(createViewSubmissionLayout);
        createViewSubmissionLayout.setHorizontalGroup(
            createViewSubmissionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createViewSubmissionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerText1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        createViewSubmissionLayout.setVerticalGroup(
            createViewSubmissionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerText1, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout tasksTabLayout = new javax.swing.GroupLayout(tasksTab);
        tasksTab.setLayout(tasksTabLayout);
        tasksTabLayout.setHorizontalGroup(
            tasksTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tasksTabLayout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addGroup(tasksTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(createViewSubmission, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 935, Short.MAX_VALUE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        tasksTabLayout.setVerticalGroup(
            tasksTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tasksTabLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(createViewSubmission, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab1", tasksTab);

        editMyProfileTab.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Helvetica", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(67, 67, 67));
        jLabel1.setText("Name");

        jLabel2.setFont(new java.awt.Font("Helvetica", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(67, 67, 67));
        jLabel2.setText("Email");

        jLabel4.setFont(new java.awt.Font("Helvetica", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(67, 67, 67));
        jLabel4.setText("Birthdate");

        jLabel5.setFont(new java.awt.Font("Helvetica", 2, 8)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(67, 67, 67));
        jLabel5.setText(" (YYYY/MM/DD)");

        jLabel6.setFont(new java.awt.Font("Helvetica", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(67, 67, 67));
        jLabel6.setText("Gender");

        jLabel7.setFont(new java.awt.Font("Helvetica", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(67, 67, 67));
        jLabel7.setText("Role");

        jLabel8.setFont(new java.awt.Font("Helvetica", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(67, 67, 67));
        jLabel8.setText("Student");

        nameField.setBackground(new java.awt.Color(255, 255, 255));
        nameField.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        nameField.setForeground(new java.awt.Color(67, 67, 67));
        nameField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        emailField.setBackground(new java.awt.Color(255, 255, 255));
        emailField.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        emailField.setForeground(new java.awt.Color(67, 67, 67));
        emailField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        birthdateField.setBackground(new java.awt.Color(255, 255, 255));
        birthdateField.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        birthdateField.setForeground(new java.awt.Color(67, 67, 67));
        birthdateField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        genderField.setBackground(new java.awt.Color(255, 255, 255));
        genderField.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        genderField.setForeground(new java.awt.Color(67, 67, 67));
        genderField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        changePasswordLink.setFont(new java.awt.Font("Helvetica", 1, 24)); // NOI18N
        changePasswordLink.setForeground(new java.awt.Color(30, 56, 115));
        changePasswordLink.setText("Change Password");
        changePasswordLink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        changePasswordLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                changePasswordLinkMouseReleased(evt);
            }
        });

        saveChangesButton.setBackground(new java.awt.Color(101, 139, 112));
        saveChangesButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saveChangesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                saveChangesButtonMouseReleased(evt);
            }
        });

        saveChangesText.setFont(new java.awt.Font("Helvetica", 1, 24)); // NOI18N
        saveChangesText.setForeground(new java.awt.Color(255, 255, 255));
        saveChangesText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        saveChangesText.setText("Save Changes");

        javax.swing.GroupLayout saveChangesButtonLayout = new javax.swing.GroupLayout(saveChangesButton);
        saveChangesButton.setLayout(saveChangesButtonLayout);
        saveChangesButtonLayout.setHorizontalGroup(
            saveChangesButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saveChangesButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(saveChangesText, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                .addContainerGap())
        );
        saveChangesButtonLayout.setVerticalGroup(
            saveChangesButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(saveChangesText, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        resetChangesButton.setBackground(new java.awt.Color(194, 130, 130));
        resetChangesButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        resetChangesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                resetChangesButtonMouseReleased(evt);
            }
        });

        resetChangesText.setFont(new java.awt.Font("Helvetica", 1, 24)); // NOI18N
        resetChangesText.setForeground(new java.awt.Color(255, 255, 255));
        resetChangesText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resetChangesText.setText("Reset Changes");

        javax.swing.GroupLayout resetChangesButtonLayout = new javax.swing.GroupLayout(resetChangesButton);
        resetChangesButton.setLayout(resetChangesButtonLayout);
        resetChangesButtonLayout.setHorizontalGroup(
            resetChangesButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resetChangesButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(resetChangesText, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                .addContainerGap())
        );
        resetChangesButtonLayout.setVerticalGroup(
            resetChangesButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(resetChangesText, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout editMyProfileTabLayout = new javax.swing.GroupLayout(editMyProfileTab);
        editMyProfileTab.setLayout(editMyProfileTabLayout);
        editMyProfileTabLayout.setHorizontalGroup(
            editMyProfileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editMyProfileTabLayout.createSequentialGroup()
                .addGap(265, 265, 265)
                .addGroup(editMyProfileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(changePasswordLink)
                    .addGroup(editMyProfileTabLayout.createSequentialGroup()
                        .addGroup(editMyProfileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(editMyProfileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(editMyProfileTabLayout.createSequentialGroup()
                        .addGroup(editMyProfileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(editMyProfileTabLayout.createSequentialGroup()
                                .addGroup(editMyProfileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(editMyProfileTabLayout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(36, 36, 36)
                                        .addComponent(jLabel5))
                                    .addComponent(birthdateField, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(68, 68, 68)
                                .addGroup(editMyProfileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(genderField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(resetChangesButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(107, 107, 107)
                        .addGroup(editMyProfileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(saveChangesButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        editMyProfileTabLayout.setVerticalGroup(
            editMyProfileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editMyProfileTabLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(editMyProfileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(editMyProfileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(editMyProfileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(23, 23, 23)
                .addGroup(editMyProfileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(birthdateField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genderField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGroup(editMyProfileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editMyProfileTabLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(changePasswordLink)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 263, Short.MAX_VALUE)
                        .addComponent(resetChangesButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(editMyProfileTabLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveChangesButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42))
        );

        jTabbedPane1.addTab("tab1", editMyProfileTab);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1220, 790));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1218, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 763, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void coursesPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_coursesPanelMouseReleased
        // TODO add your handling code here:
        // change icon to img11, others become img14, img16, img18, img20 respectively
        // change bg color of panel to (67,67,67), text to (219,219,219) and panel of others to (35,35,35) and text of others to (112,110,110)
        coursesIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/img30_courses_selected.png")));
        coursesPanel.setBackground(new java.awt.Color(67, 67, 67));
        coursesText.setForeground(new java.awt.Color(219, 219, 219));

        tasksIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/img33_tasks_unselected.png")));
        tasksPanel.setBackground(new java.awt.Color(35, 35, 35));
        tasksText.setForeground(new java.awt.Color(112, 110, 110));

        editMyProfileIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/img35_editMyProfile_unselected.png")));
        editMyProfilePanel.setBackground(new java.awt.Color(35, 35, 35));
        editMyProfileText.setForeground(new java.awt.Color(112, 110, 110));
        
        // headertext changes to Dashboard
        headerText.setText("Course Selection");

        // change index of selected tab to 0
        jTabbedPane1.setSelectedIndex(0);

    }//GEN-LAST:event_coursesPanelMouseReleased

    private void tasksPanelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tasksPanelKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tasksPanelKeyReleased

    private void editMyProfilePanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMyProfilePanelMouseReleased
        // TODO add your handling code here:
        // change icon to img15, others become img12, img14, img18, img20 respectively
        // change bg color of panel to (67,67,67), text to (219,219,219) and panel of others to (35,35,35) and text of others to (112,110,110)
        editMyProfileIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/img34_editMyProfile_selected.png")));
        editMyProfilePanel.setBackground(new java.awt.Color(67, 67, 67));
        editMyProfileText.setForeground(new java.awt.Color(219, 219, 219));

        coursesIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/img31_courses_unselected.png")));
        coursesPanel.setBackground(new java.awt.Color(35, 35, 35));
        coursesText.setForeground(new java.awt.Color(112, 110, 110));

        tasksIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/img33_tasks_unselected.png")));
        tasksPanel.setBackground(new java.awt.Color(35, 35, 35));
        tasksText.setForeground(new java.awt.Color(112, 110, 110));
        
        // headertext changes to Manage Teachers
        headerText.setText("Tasks");

        // switch to manage teachers panel
        jTabbedPane1.setSelectedIndex(2);
        
    }//GEN-LAST:event_editMyProfilePanelMouseReleased

    private void tasksPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tasksPanelMouseReleased
        // TODO add your handling code here:
        // change assign courses icon to img13, others become img12, img16, img18, img20 respectively
        // change bg color of panel to (67,67,67), text to (219,219,219) and panel of others to (35,35,35) and text of others to (112,110,110)
        tasksIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/img32_tasks_selected.png")));
        tasksPanel.setBackground(new java.awt.Color(67, 67, 67));
        tasksText.setForeground(new java.awt.Color(219, 219, 219));

        coursesIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/img31_courses_unselected.png")));
        coursesPanel.setBackground(new java.awt.Color(35, 35, 35));
        coursesText.setForeground(new java.awt.Color(112, 110, 110));

        editMyProfileIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/img35_editMyProfile_unselected.png")));
        editMyProfilePanel.setBackground(new java.awt.Color(35, 35, 35));
        editMyProfileText.setForeground(new java.awt.Color(112, 110, 110));

        // headertext changes to Manage Students
        headerText.setText("Attendance");

        // switch to manage students panel
        jTabbedPane1.setSelectedIndex(1);
        
    }//GEN-LAST:event_tasksPanelMouseReleased

    private void signOutPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signOutPanelMouseReleased
        // TODO add your handling code here:
        // current user = null, current course = null

        Manager manager = Manager.getInstance();
        
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_signOutPanelMouseReleased

    private void saveChangesButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveChangesButtonMouseReleased
        // Get user input from the fields
        String name = nameField.getText();
        String email = emailField.getText();
        String birthdateStr = birthdateField.getText();
        String gender = genderField.getText();

        // Input validation
        if (name.trim().isEmpty() || email.trim().isEmpty() || birthdateStr.trim().isEmpty() || gender.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in all fields.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            Date birthdate = Date.valueOf(birthdateStr); //Attempt to parse birthdate

            // Confirmation dialog
            int result = JOptionPane.showConfirmDialog(this, "Are you sure you want to save these changes?", "Confirm Changes", JOptionPane.YES_NO_OPTION);
            if (result == JOptionPane.YES_OPTION) {
                // Update the user information in the database
                UserDAO userDAO = new UserDAO();
                originalUser.setName(name);
                originalUser.setEmail(email);
                originalUser.setBirthdate(birthdate);
                originalUser.setGender(gender);
                userDAO.update(originalUser); // Update method that takes User object

                JOptionPane.showMessageDialog(this, "Changes saved successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
                // Optionally, refresh the displayed information
                populateFields();
            }
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, "Invalid date format. Please use YYYY-MM-DD.", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "An error occurred while saving changes.", "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_saveChangesButtonMouseReleased

    private void resetChangesButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetChangesButtonMouseReleased
        // TODO add your handling code here:
        // prompts user if they would like to reset
        int result = JOptionPane.showConfirmDialog(this, "Are you sure you want to reset all changes?", "Confirm Reset", JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            // Reset the fields to their original values
            populateFields();
        }
        
    }//GEN-LAST:event_resetChangesButtonMouseReleased

    private void changePasswordLinkMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changePasswordLinkMouseReleased
        // TODO add your handling code here:

        // pass user find by id via userDAO, where id comes from original user to update password
        UserDAO userDAO = null;
        try {
            userDAO = new UserDAO();
        } catch (SQLException ex) {
            Logger.getLogger(StudentDashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        UpdatePassword updatePassword = new UpdatePassword(userDAO.findById(originalUser.getUserID()));
        updatePassword.setVisible(true);

        // have the currentUser be updated by the id of the currentUser (because the password changed in the database but the user object in manager doesnt show this)


    }//GEN-LAST:event_changePasswordLinkMouseReleased

    private void tasksTableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tasksTableMouseReleased
        // get the selected row, if the status is not SUBMITTED, the createViewSubmission bg color should be 30, 56, 115 and the text should be "Create Submission", otherwise (if submitted), then 112, 110, 110 and "View Submission"
        int selectedRow = tasksTable.getSelectedRow();
        if (selectedRow != -1) {
            String status = tasksTable.getValueAt(selectedRow, 4).toString(); // status is in the 4th column (index 3)
            if (status.equals("SUBMITTED")) {
                createViewSubmission.setBackground(new java.awt.Color(112, 110, 110));
                headerText1.setText("View Submission");
            } else {
                createViewSubmission.setBackground(new java.awt.Color(30, 56, 115));
                headerText1.setText("Create Submission");
            }
        }
        
    }//GEN-LAST:event_tasksTableMouseReleased

    private void createViewSubmissionMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createViewSubmissionMouseReleased
        int selectedRow = tasksTable.getSelectedRow();

        if (selectedRow != -1) {
            int submissionId = (int) tasksTable.getValueAt(selectedRow, 0); // Submission ID is in the first column (index 0)
            String status = tasksTable.getValueAt(selectedRow, 4).toString();
    
            try {
                TaskSubmissionDAO taskSubmissionDAO = new TaskSubmissionDAO();
                TaskSubmission submission = taskSubmissionDAO.findById(submissionId); // Directly fetch by submission ID
    
                if (submission != null) {
                    if (status.equals("SUBMITTED")) {
                        ViewSubmissionAsStudent viewSubmission = new ViewSubmissionAsStudent(submission);
                        viewSubmission.setVisible(true);
                        refreshTasksTable();
                    } else {
                        // Create submission
                        refreshTasksTable();
                        if (submission.getStatus() == TaskStatus.NONE) { // Check if status is NONE
                            CreateSubmission createSubmission = new CreateSubmission(submission);
                            createSubmission.setVisible(true);
                        } else {
                            JOptionPane.showMessageDialog(this, "Submission already exists.", "Error", JOptionPane.ERROR_MESSAGE);
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Submission not found.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "An error occurred.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select a task.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_createViewSubmissionMouseReleased

    private void populateFields() {
        fullnameText.setText(originalUser.getName());
        nameField.setText(originalUser.getName());
        emailField.setText(originalUser.getEmail());
        birthdateField.setText(originalUser.getBirthdate().toString());
        genderField.setText(originalUser.getGender());
        // Password field remains empty
    }

    private void populateTables() {
        // display courses in table
        
        // display all tasks for each course, for each student task in each roster of each course, display course code, course title, task title, status, action (just string with "create submission" if status is not submitted or "view submission" if status is submitted), and grade (- if not submitted, actual grade / 100 if submitted)
        // find tasks via findByStudentId in TaskSubmissionDAO
        try {
            CourseDAO courseDAO = new CourseDAO();
            TaskSubmissionDAO taskSubmissionDAO = new TaskSubmissionDAO();
            StudentSessionDAO studentSessionDAO = new StudentSessionDAO();
            ArrayList<TaskSubmission> submissions = taskSubmissionDAO.findByStudentId(originalUser.getUserID());

            
            javax.swing.table.DefaultTableModel courseModel = (javax.swing.table.DefaultTableModel) coursesTable.getModel();
            courseModel.setRowCount(0); // Clear existing rows
            
            javax.swing.table.DefaultTableModel taskModel = (javax.swing.table.DefaultTableModel) tasksTable.getModel();
            taskModel.setRowCount(0); // Clear existing rows

            ArrayList<Course> studentCourses = courseDAO.findCoursesByStudentId(originalUser.getUserID());

            // Populate courses table with ONLY the student's courses
            for (Course course : studentCourses) {
                String attendance = String.format("%.2f", studentSessionDAO.getAttendanceRateForStudentInCourse(originalUser.getUserID(), course.getCourseId()) * 100) + "%";

                Object[] courseRow = new Object[]{
                        course.getCourseCode(),
                        course.getCourseTitle(),
                        String.format("%.2f", taskSubmissionDAO.getAverageGradeForStudentInCourse(originalUser.getUserID(), course.getCourseId())),
                        attendance
                };
                courseModel.addRow(courseRow);
            }
            
            // Populate tasks table
            for (TaskSubmission submission : submissions) {
                String courseCode = taskSubmissionDAO.findCourseCodeBySubmissionId(submission.getSubmissionId());
                String courseTitle = taskSubmissionDAO.findCourseTitleBySubmissionId(submission.getSubmissionId());
                String taskTitle = taskSubmissionDAO.findTaskTitleBySubmissionId(submission.getSubmissionId());
    
                // Handle cases where data might be missing
                courseCode = courseCode == null ? "-" : courseCode;
                courseTitle = courseTitle == null ? "-" : courseTitle;
                taskTitle = taskTitle == null ? "-" : taskTitle;
    
                Object[] taskRow = new Object[]{
                        submission.getSubmissionId(),
                        courseCode,
                        courseTitle,
                        taskTitle,
                        submission.getStatus().toString(),
                        submission.getSubmissionGrade() == null ? "-" : submission.getSubmissionGrade()
                };
                taskModel.addRow(taskRow);
            }
    

        } catch (SQLException ex) {
            Logger.getLogger(StudentDashboard.class.getName()).log(Level.SEVERE, null, ex);
        }        
    }

    private void refreshTasksTable() {
        populateTables(); // Call your existing method to repopulate the table
    }



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CampusMateLogo;
    private javax.swing.JTextField birthdateField;
    private javax.swing.JLabel changePasswordLink;
    private javax.swing.JLabel coursesIcon;
    private javax.swing.JPanel coursesPanel;
    private javax.swing.JPanel coursesTab;
    private javax.swing.JTable coursesTable;
    private javax.swing.JLabel coursesText;
    private javax.swing.JPanel createViewSubmission;
    private javax.swing.JLabel editMyProfileIcon;
    private javax.swing.JPanel editMyProfilePanel;
    private javax.swing.JPanel editMyProfileTab;
    private javax.swing.JLabel editMyProfileText;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel fullnameText;
    private javax.swing.JTextField genderField;
    private javax.swing.JPanel headerDivider;
    private javax.swing.JPanel headerPanel1;
    private javax.swing.JLabel headerText;
    private javax.swing.JLabel headerText1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField nameField;
    private javax.swing.JPanel resetChangesButton;
    private javax.swing.JLabel resetChangesText;
    private javax.swing.JPanel saveChangesButton;
    private javax.swing.JLabel saveChangesText;
    private javax.swing.JPanel signOutPanel;
    private javax.swing.JLabel tasksIcon;
    private javax.swing.JPanel tasksPanel;
    private javax.swing.JPanel tasksTab;
    private javax.swing.JTable tasksTable;
    private javax.swing.JLabel tasksText;
    // End of variables declaration//GEN-END:variables
}
