/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MyApps;

import javax.swing.JOptionPane;

import MyLibs.Task;
import MyLibs.TaskDAO;
import MyLibs.TaskSubmission;

/**
 *
 * @author allen
 */
public class ViewSubmissionAsStudent extends javax.swing.JFrame {

    private TaskSubmission submission;
    
    /**
     * Creates new form ViewSubmissionAsStudent
     */
    public ViewSubmissionAsStudent(TaskSubmission submission) {
        initComponents();
        this.submission = submission;
        populateFields();
    }

    private void populateFields() {
        try {
            if (submission != null) {
                TaskDAO taskDAO = new TaskDAO();
                Task task = taskDAO.findById(submission.getTaskId());

                if (task != null) {
                    taskTitleText.setText(task.getTaskTitle());
                    taskPromptArea.setText(task.getTaskPrompt());
                } else {
                    taskTitleText.setText("Task not found");
                    taskPromptArea.setText("");
                }

                submissionTitleText.setText(submission.getSubmissionTitle());
                submissionContentArea.setText(submission.getSubmissionContent());
            } else {
                // Handle case where submission is null
                JOptionPane.showMessageDialog(this, "Submission data is missing.", "Error", JOptionPane.ERROR_MESSAGE);
                this.dispose(); // Close the window if submission data is missing
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "An error occurred.", "Error", JOptionPane.ERROR_MESSAGE);
            this.dispose(); // Close the window if an error occurs
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        taskTitleText = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taskPromptArea = new javax.swing.JTextArea();
        submissionTitleText = new javax.swing.JLabel();
        closeWindowButton = new javax.swing.JPanel();
        closeWindowText = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        submissionContentArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 600));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(249, 249, 249));

        jPanel2.setBackground(new java.awt.Color(249, 249, 249));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        taskTitleText.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        taskTitleText.setForeground(new java.awt.Color(67, 67, 67));
        taskTitleText.setText("Task Title");

        taskPromptArea.setEditable(false);
        taskPromptArea.setBackground(new java.awt.Color(255, 255, 255));
        taskPromptArea.setColumns(20);
        taskPromptArea.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        taskPromptArea.setForeground(new java.awt.Color(67, 67, 67));
        taskPromptArea.setLineWrap(true);
        taskPromptArea.setRows(5);
        jScrollPane1.setViewportView(taskPromptArea);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(taskTitleText, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(taskTitleText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        submissionTitleText.setFont(new java.awt.Font("Helvetica", 1, 24)); // NOI18N
        submissionTitleText.setForeground(new java.awt.Color(67, 67, 67));
        submissionTitleText.setText("Submission Title");

        closeWindowButton.setBackground(new java.awt.Color(194, 130, 130));
        closeWindowButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeWindowButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                closeWindowButtonMouseReleased(evt);
            }
        });

        closeWindowText.setFont(new java.awt.Font("Helvetica", 1, 24)); // NOI18N
        closeWindowText.setForeground(new java.awt.Color(255, 255, 255));
        closeWindowText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeWindowText.setText("Close Window");

        javax.swing.GroupLayout closeWindowButtonLayout = new javax.swing.GroupLayout(closeWindowButton);
        closeWindowButton.setLayout(closeWindowButtonLayout);
        closeWindowButtonLayout.setHorizontalGroup(
            closeWindowButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, closeWindowButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(closeWindowText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        closeWindowButtonLayout.setVerticalGroup(
            closeWindowButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(closeWindowButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(closeWindowText)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        submissionContentArea.setEditable(false);
        submissionContentArea.setBackground(new java.awt.Color(255, 255, 255));
        submissionContentArea.setColumns(20);
        submissionContentArea.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        submissionContentArea.setForeground(new java.awt.Color(67, 67, 67));
        submissionContentArea.setLineWrap(true);
        submissionContentArea.setRows(5);
        jScrollPane2.setViewportView(submissionContentArea);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(submissionTitleText, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(closeWindowButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(submissionTitleText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(closeWindowButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeWindowButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeWindowButtonMouseReleased
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_closeWindowButtonMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewSubmissionAsStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewSubmissionAsStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewSubmissionAsStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewSubmissionAsStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // new ViewSubmissionAsStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel closeWindowButton;
    private javax.swing.JLabel closeWindowText;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea submissionContentArea;
    private javax.swing.JLabel submissionTitleText;
    private javax.swing.JTextArea taskPromptArea;
    private javax.swing.JLabel taskTitleText;
    // End of variables declaration//GEN-END:variables
}
